public class Address {
    public void homeAddress(){
     string yourName = 'Funda'; 
     integer totalOffFamily = 5;
     string houseName = 'Yazici';
     integer houseNumber = 739;
     string streetName = 'Red Oak';
     string cityName = 'Naperville';
     string stateName = 'IL';
     string stateISOCode = '53535353';
     string countryName = 'USA';
     string countryISOCode = '35353535';
     string zipCode = '60563';
     Boolean currentHomeorNot = true;
     
     system.debug('My name is ' + yourName);
     system.debug('Total family number is ' + totalOffFamily);
     system.debug('My house name is ' + houseName);
     system.debug('My house number is ' + houseNumber);
     system.debug('My street is ' + streetName);
     system.debug('My city is ' + cityName);
     system.debug('State ' + stateName);
     system.debug('State ISO code is ' + stateISOCode);
     system.debug('The country that I am living in ' + countryName);
     system.debug('My country ISO code is ' + countryISOCode);
     system.debug('The zip code is ' + zipCode);
     system.debug('This is my current home ' + currentHomeorNot);






    }
    
}