public class MathematicalClass {
    public integer Addition(integer a, Integer b) {
        integer add = a+b;
        return add;
        
    }
    public integer subtraction(integer a, integer b){
        integer sub = a-b;
        return sub;

    }
    public integer multipication (integer a, integer b){
        integer mult = a*b;
        return mult;
    }
    public decimal division (integer a, integer b){
        decimal div = a/b;
        return div;

    }
        

}