MathematicalClass math = new MathematicalClass();

integer ad = math.Addition(25, 25);
system.debug('The total of 25 and 25 is = ' + ad);

integer sb = math.subtraction(50, 25);
system.debug('differences is between 50 and 25 is = ' + sb);

integer ml = math.multipication(3, 5);
system.debug('multiplying of 3 and 5 is = ' + ml);

decimal dv  = math.division(50, 5);
system.debug('58 divided by 2 is =  ' + dv);
